### ISSUE TITLE
geerlinguy ansible role versions

### ISSUE THREAD

**Issue by ax0n-pr1me** [Thomvaill/tads-boilerplate#11]
**Describe the bug**
setup fails on `./tads ansible-playbook localhost provision`

reports that pip is not found - apperas to be an error with the gerrlingguy.pip role. Solved this issue by updating the 
`requirements.yaml` to the following:

```
###
# ansible-galaxy requirements
##
# Automatically installed before each T.A.D.S. Ansible command
##

- src: geerlingguy.pip
  version: 2.1.0

- src: geerlingguy.docker
  version: 3.1.2

```

**To Reproduce**
Follow the exact steps in the README.

**Expected behavior**
Expected deployment to work as shown in demo video.

**Environment (please complete the following information):**
 - OS/distro: Ubuntu 20.04 desktop
 - Ansible version: 2.9.6
 - Terraform version: v0.15.5
 - Cloud provider: n/a
 - Vagrant version: 2.2.6

**Additional context**
note the default version of terraform installed by the script is now outdated.

**Comment by ax0n-pr1me** [comment]
also seeing some other issues that may be related... for example the example-app will service will not deploy properly, and gives the following error:

```
invalid mount {Destination:example_app_config Type:bind Source:/var/lib/docker/containers/17c307cf5e86612af32f22bec02f49d53a9d2750d2f2b055399bac7246a0daf7/mounts/secrets/yswm4jimsbpwfcdggawjst6j0 Options:[rbind ro]}: mount destination example_app_config not absolute: unknown" 
```

and could be related to this:

https://github.com/moby/moby/issues/42480

**Comment by ivoba** [comment]
The following happened on Ubuntu 20.04.
For the provided versions:

```
- src: geerlingguy.pip
  version: 1.3.0

- src: geerlingguy.docker
  version: 2.5.3
```

i had to install python3-pip on cloud machine, provision-00-common.yml:

```
    - name: Install Pip
      become: True
      apt:
        name: python3-pip
```

and tell geerlingguy.pip where the bin is, provision-01-docker.yml:

```
    - role: geerlingguy.pip
      pip_package: python3-pip
```
